version: "3.9"
services:
  pgapoi:
    container_name: pgapoi
    image: postgres
    volumes:
      - pg-apoi9:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'apoi'
    ports:
      - 5433:5433
    command: -p 5433

  appointment-service:
    build: appointment-service
    container_name: apoi
    environment:
      PG_URL: 'postgres://user:pass@pgapoi:5433/apoi'
    ports:
      - "8087:8087"
    depends_on:
      - pgapoi

volumes:
  pg-apoi9: