version: "3.7"
services:
  web:
    image: chat-bot-backend
    container_name: bot_management_api
    ports:
      - 8081:8081
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./config/config.yml:/app/config/config.yml

  mysql:
    image: mysql:5.7
    container_name: chat_bot_backend_mysql
    command: mysqld --user=root
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
