app:
  name: 'chat-bot-backend'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: '8087'
  read_timeout: 5
  write_timeout: 5
  shutdown_timeout: 3

postgres:
  pool_max: 2
  url: "postgres://user:pass@pgapoi:5433/apoi"

logger:
  log_level: 'debug'
  rollbar_env: 'chat-bot-backend'